### ISSUE TITLE
should be a no-op on unknown platforms

### ISSUE THREAD

**Issue by cgwalters** [openshift/cluster-storage-operator#13]
See https://github.com/openshift/installer/pull/1112 and e.g. https://github.com/openshift/machine-config-operator/pull/340 - rather than erroring out, just do nothing if the platform is unknown.

This will aid porting to new platforms.

Concretely today this operator errors out on libvirt, but as we e.g. bring up GCP and other platforms it will be less painful if operators like this one don't error out.

(We probably do want to surface their non-operation though in a visible way)

**Comment by wongma7** [comment]
should be fixed by https://github.com/openshift/cluster-storage-operator/pull/14, ty
