### ISSUE TITLE
Read platform from Infrastructure instead of install-config

### ISSUE THREAD

**Issue by wongma7** [openshift/cluster-storage-operator#18]
https://github.com/openshift/api/blob/01e157580c39b8e5a266a1d747bfbed1e1c5a854/config/v1/types_infrastructure.go#L31 instead of https://github.com/openshift/installer/blob/8173c233bc05045e70c6caaaa9589e23c5465170/pkg/types/installconfig.go#L52.

**Comment by gnufied** [comment]
I will do this as part of vsphere configuration.
