### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by maci0** [openshift/cluster-storage-operator#26]
Should be able to set the encryption parameter somewhere. Maybe a config map?

**Comment by wongma7** [comment]
We currently intend for the bundled default `gp2` storageclass to be unconfigurable... Idea being that if you want to configure one with e.g. parameter `encryption: true` https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs you must create one yourself and make it default instead https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/.

Having the class unconfigurable simplifies the operator a bit, also it may help us debug if (mostly) everyone's `gp2` storageclass looks exactly the same.

**Comment by wongma7** [comment]
https://github.com/openshift/cluster-storage-operator/pull/32 has merged to make encrypted the default. previous comment still applies: to configure, create a new storageclass
