### ISSUE TITLE
HTTPS_PROXY ENV missing in vmware-vsphere-csi-driver-operator

### ISSUE THREAD

**Issue by vittico** [openshift/cluster-storage-operator#291]
Hello,

In a not-so-common environment we need the operator to reach vmware API enpoint through a proxy, it seems there is no proxy env set. The proxy is configured clusterwide.

I am honestly not sure if adding the environment variable would make anything work, as the driver would still need to be aware of the variable correct? Also not sure if this is relevant to the cluster-storage-operator or on VMWare side of things maybe?

~~~
oc rsh -n openshift-cluster-csi-drivers vmware-vsphere-csi-driver-operator-57bc458d9c-nmwf5
sh-4.4$ curl -vk -m 5 https://xxx.xxxx.xxx.xxx/sdk
*   Trying 999.999.999.999...
* TCP_NODELAY set
* Connection timed out after 5001 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 5001 milliseconds
~~~

~~~
$ oc rsh -n openshift-cluster-csi-drivers vmware-vsphere-csi-driver-operator-57bc458d9c-nmwf5
sh-4.4$ HTTPS_PROXY=http://yyy.yyy.yyy.yyy:3128 curl -k https://xxx.xxx.xxx.xxx | head -5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3618  100  3618    0     0   153k      0 --:--:-- --:--:-- --:--:--  153k
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
 <head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
~~~

**Comment by jsafrane** [comment]
http proxy *should* be injected into the operator Pod when OpenShift global HTTP proxy is configured:  https://docs.openshift.com/container-platform/4.10/networking/enable-cluster-wide-proxy.html#enable-cluster-wide-proxy

It is a bug if the proxy is not injected.

We do not offer any other way how to configure proxy for individual components, it would be very messy.

**Comment by vittico** [comment]
@jsafrane sorry for my delayed answer.

Correct, the environment variables are not injected in the operator pod it seems, and yes the cluster-wide setting is enabled. Is this the correct place to fill the bug?

**Comment by jsafrane** [comment]
We're fixing it in https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/114 for OCP 4.10, 4.11 has been already fixed by the parent PR.
